Feature: Block page
  Scenario: should show title, summary, and transactions
    Given I'm on page "/block/6524861224470851795"
    Then I should see "6524861224470851795" in "top title" element
    And I should see "Block with 103 transactions" in "sub title" element
    And I should see "Home Block 6524861224470851795" in "breadcrumb" element
    And I should see table "summary" containing:
      | Block ID               | 6524861224470851795        |
      | Height                 | 1                          |
      | Number of transactions | 103                        |
      | Confirmations          | /\d+/                      |
      | Reward                 | 0 F39                      |
      | Total Fee              | 0 F39                      |
      | Total Forged           | 0 F39                      |
      | Total Amount           | 100,000,000 F39            |
      | Timestamp              | /2016\/05\/24 \d\d:00:00/  |
      | Generated by           | 1085993630748340485F       |
      | Version                | 0                          |
    And I should see table "transactions table" with 20 rows starting with:
      | Transaction ID       | Date                      | Sender               | Recipient             | Amount          | Fee   | Confirm.      |
      |----------------------|---------------------------|----------------------|-----------------------|-----------------|-------|---------------|
      | /\d{18,20}/          | /2016\/05\/24 \d\d:00:00/ | 1085993630748340485F | 16313739661670634666F	| 100,000,000 F39 | 0 F39 | Confirmed     |
      | /\d{18,20}/          | /2016\/05\/24 \d\d:00:00/ | /genesis_\d{1,3}/    | Delegate registration | 0 F39           | 0 F39 | Confirmed     |
      | /\d{18,20}/          | /2016\/05\/24 \d\d:00:00/ | /genesis_\d{1,3}/    | Delegate registration | 0 F39           | 0 F39 | Confirmed     |
      | /\d{18,20}/          | /2016\/05\/24 \d\d:00:00/ | /genesis_\d{1,3}/    | Delegate registration | 0 F39           | 0 F39 | Confirmed     |
      | /\d{18,20}/          | /2016\/05\/24 \d\d:00:00/ | /genesis_\d{1,3}/    | Delegate registration | 0 F39           | 0 F39 | Confirmed     |
  

  Scenario: should allow to load more transactions
    Given I'm on page "/block/6524861224470851795"
    When I scroll to "btn next"
    And I click "btn next"
    Then I should see table "transactions table" with 20 rows

  Scenario: should allow to load less transactions
    Given I'm on page "/block/6524861224470851795"
    When I scroll to "btn next"
    And I click "btn next"
    And I should see table "transactions" with 20 rows
    When I scroll to "btn prev"
    And I click "btn prev"
    Then I should see table "transactions" with 20 rows
